### ISSUE TITLE
服务器问题

### ISSUE THREAD

**Issue by xingnengmao666** [sensen1234/SenCraft#5]
![image](https://user-images.githubusercontent.com/88268143/224477788-a40b454c-fc61-4f52-b4cb-87637080a679.png)
在这张图中可以看到，/cmi skin off指令无法使用，而且服务器无法识别正版玩家的皮肤，恳请解决

**Comment by sensen1234** [comment]
未开放/cmi skin
请使用/skin set [id]



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月11日(周六) 下午5:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [sensen1234/SenCraft] 服务器问题 (Issue #5)




 

 在这张图中可以看到，/cmi skin off指令无法使用，而且服务器无法识别正版玩家的皮肤，恳请解决

**Comment by sensen1234** [comment]
未开放cmi skin
请使用skin set
实测可以获取正版ID皮肤，建议等namemc update你的skin后再试试
